language: php

dist: xenial

services:
  - mysql
  - postgresql

env:
  global:
    - TRAVIS_NODE_VERSION="10"

matrix:
  include:
    - php: 7.1
      env: DB=MYSQL RECIPE_VERSION="4.5.x-dev" PHPUNIT_TEST=1
    - php: 7.2
      env: DB=PGSQL RECIPE_VERSION="4.5.x-dev" PHPUNIT_TEST=1
    - php: 7.3
      env: DB=MYSQL RECIPE_VERSION="4.6.x-dev" PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.4
      env: DB=MYSQL RECIPE_VERSION="4.x-dev" PHPUNIT_TEST=1 PHPUNIT_COVERAGE_TEST=1

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - export PATH=~/.composer/vendor/bin:$PATH
  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Install composer
  - composer validate
  - if [[ $DB == PGSQL ]]; then composer require --prefer-dist --no-update silverstripe/postgresql:^2; fi
  - composer require silverstripe/recipe-cms "$RECIPE_VERSION" --no-update
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src tests; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml -F php; fi
